#!/bin/bash
# Copyright (C) 2015 Martín Cigorraga <archlinux.us: msx>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the Affero GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Check mouse event
case $BLOCK_BUTTON in
    4) pamixer --unmute ;; # scroll up unmute
	5) pamixer --mute ;; # scroll down mute
esac


# Determine mic's state
if [[ $(pamixer --get-mute) == "true" ]]; then
	state="off"
else
	state="on"
fi
#/usr/bin/pactl list sources | grep -q "Mute: no" && [[ $? -eq 0 ]] && state="on";  # If you rather go with PulseAudio


# Toggle mic's state
case $state in
    off)
    echo "  " " muted ";
    echo
    echo \#005FD7;  # Soft blue
    exit 0;
    ;;
    *)
    echo "     " " OPEN   ";
    #echo "      ";
    exit 33;
    ;;
esac

exit 0;
